config/routes.rb
Rails.application.routes.draw do
  resources :gatherings, only: [:index, :create]
  resources :informations, only: [:index, :create, :show]
  resources :reactions, only: [:index, :create]
  resources :subscribers, only: [:create]

  root to: "pages#cover"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gathering.rb
class Gathering < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :information
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gatherings_controller.rb
class GatheringsController < ApplicationController
  def index
    @gatherings = Gathering.all
    @gathering = Gathering.new
  end

  def create
    @gathering = Gathering.new(gathering_params)

    if @gathering.save
      flash[:sucess] = "merci pour l'info!"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = @gathering.errors_to_sentence
      redirect_to root_url
    end
  end


  protected
  def gathering_params
    params.require(:gathering).permit(:date, :time, :location, :content)
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def index
    @information = Information.new
    @informations = Information.all.order('created_at DESC')
  end

  def show
    @information = Information.find(params[:id])
  end

  def create
    @information = Information.new(information_params)

    if @information.save
      flash[:sucess] = "merci pour l'info!"
      redirect_to @information, notice: "merci pour l'info!"
    else
      flash[:alert] = @information.errors_to_sentence
      redirect_to root_url
    end
  end


  protected
  def information_params
    params.require(:information).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def cover
    @informations = Information.limit(1).order("RANDOM()")
    @gatherings = Gathering.limit(5).order("RANDOM()") #order(date: :desc)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def index
    @information = Information.order('RANDOM()').first
    @reactions = Reaction.all.order('created_at DESC')
  end

  def create
    @reaction = Reaction.new(reaction_params)

    if @reaction.save
      flash[:sucess] = "merci pour ton avis, ça fait réfléchir!"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = @reaction.errors_to_sentence
      redirect_back fallback_location: root_path
    end
  end


  protected
  def reaction_params
    params.require(:reaction).permit(:content, :author, :information_id)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      flash[:sucess] = "merci et à bientôt dans ta boîte aux lettres!"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = @subscriber.errors_to_sentence
      redirect_back fallback_location: root_path
    end
  end


  protected
  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gatherings_helper.rb
module GatheringsHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/gatherings/index.html.slim
.title
  .title-content
    = "Événements"

.new
  .new-content
    = form_for @gathering do |f|
      .new-content-line
        .new-content-label
          = f.label "date"
        .new-content-field
          = f.date_field :date
          i= f.label :starts_at, "(ex: 28/09/2018)"
      .new-content-line
        .new-content-label
          = f.label "heure"
        .new-content-field
          = f.time_field :time
          i= f.label :hour, "(ex: 19:00)"
      .new-content-line
        .new-content-label
          = f.label "localisation"
        .new-content-field
          = f.text_field :location
      .new-content-line
        .new-content-label
          = f.label "description"
        .new-content-field
          = f.text_area :content
      .new-content-line
        .new-content-tag
          = f.submit "   "
          = "je souhaite diffuser ce rassemblement"

.index
  - @gatherings.each do |gathering|
    .index-content
      .index-content-date
        = gathering.date
      .index-content-middle
        = gathering.content
        br
        b= gathering.location
      .index-content-bottom
        = gathering.time.strftime("%R")

app/views/gatherings/new.html.slim
.title
  .title-content
    = "Rassemblement général!"

.new
  .new-content
    .new-content-line
      .new-content-label
        = "date:"
      .new-content-field
      = "..............."
    .new-content-line
      .new-content-label
        = "ville:"
      .new-content-field
        = "..............."
    .new-content-line
      .new-content-label
        = "place:"
      .new-content-field
        = "..............."
    .new-content-line
      .new-content-label
        = "description:"
      .new-content-field
        = "..............."
    .new-content-line
      .new-content-tag
        = "[] je souhaite diffuser ce rassemblement"

.index
  .index-content
    .index-content-date
      = "le 18/11/2019"
    .index-content-description
      = "..........."
    .index-content-time
      = "18h"

  .index-content
    .index-content-date
      = "le 18/11/2019"
    .index-content-description
      = "..........."
    .index-content-time
      = "18h"

  .index-content
    .index-content-date
      = "le 18/11/2019"
    .index-content-description
      = "..........."
    .index-content-time
      = "18h"

  .index-content
    .index-content-date
      = "le 18/11/2019"
    .index-content-description
      = "..........."
    .index-content-time
      = "18h"

app/views/informations/index.html.slim
.title
  .title-content
    = "Informations"

.new
  .new-content
    = form_for @information, url: {action: "create"}, html: {class: "nifty_form"} do |f|
      .new-content-label
        = f.label "information:"
      .new-content-field
        = f.text_area :content
      .new-content-tag
        = f.submit "   "
        = "je souhaite diffuser cet info"

.index
  - @informations.each do |information|
    .index-content
      .index-content-middle
        = information.content
      .index-content-bottom
        = link_to "réagis", information_path(information.id)

app/views/informations/new.html.slim
.title
  .title-content
    = "L'actu c'est ici !"

.new
  .new-content
    .new-content-label
      = "information:"
    .new-content-field
    = "..............."
    br
    = "..............."
    br
    = "..............."
    .new-content-tag
      = "[] je souhaite diffuser cet info"

.index
  .index-content
    .index-content-description
      = "..........."
    .index-content-time
      = "réagis"

  .index-content
    .index-content-description
      = "..........."
    .index-content-time
      = "réagis"

  .index-content
    .index-content-description
      = "..........."
    .index-content-time
      = "réagis"

  .index-content
    .index-content-description
      = "..........."
    .index-content-time
      = "réagis"

app/views/informations/show.html.slim
.title
  .title-content
    = "Ça s'discute, ça s'discute..."

.show
  .show-content
    = @information.content 

.index
  - if reactions = Reaction.where(information_id: @information.id)
    - reactions.each do |reaction|
      .index-content
        .index-content-middle
          = reaction.content
        .index-content-bottom
          = reaction.author

  .index-content
    = form_for Reaction.new do |f|
      .index-content-middle-new
        = f.label "réaction:"
        = f.text_area :content
        br
        = f.label "vos initiales comme signature numérique:"
        = f.text_field :author
        = f.hidden_field :information_id, :value => @information.id
      .index-content-bottom-new
        = f.submit "diffuser ma réaction"

app/views/layouts/_header.html.slim
.header
  .header-title
  .header-subtitle
    = link_to "À toi la parole!", root_path
  .header-navigation
    .header-navigation-content
      = link_to "rassemble", gatherings_path
    .header-navigation-content
      = link_to "informe", informations_path
    .header-navigation-content
      = link_to "reagis", reactions_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title= "mon journal"
    meta name="viewport" content="width=device-width, initial-scale=1" /
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body

    .body-content
      = render partial: "layouts/header"

      p.alert= alert
      p.notice= notice

      = yield

app/views/pages/cover.html.slim
.title
  .title-content
    = "À la Une"

- @gatherings.each do |gathering|
  .index
    .index-title
      = "Rencontres prévues"
    .index-content
      .index-content-date
        = gathering.date
      .index-content-middle
        = gathering.content
        br
        b= gathering.location
      .index-content-bottom
        = gathering.time.strftime("%R")




- @informations.each do |information|
  .show
    .show-content
      = information.content

  .index
    - if reactions = Reaction.where(information_id: information.id)
      - reactions.each do |reaction|
        .index-content
          .index-content-middle
            = reaction.content
          .index-content-bottom
            = reaction.author

    .index-content
      = form_for Reaction.new do |f|
        .index-content-middle-new
          = f.label "réaction:"
          = f.text_area :content
          br
          = f.label "vos initiales comme signature numérique:"
          = f.text_field :author
          = f.hidden_field :information_id, :value => information.id
        .index-content-bottom-new
          = f.submit "diffuser ma réaction"




.more
  = form_for Subscriber.new do |f|
    .more-content
      = f.label "liste d'attente pour reçevoir le journal directement dans ta boîte mail 1 fois par mois!"
      br
      = f.text_field :email, placeholder: "ton adresse mail"
      br
      = f.submit "s'inscrire"

  .more-content
    = "Rédacteur"
    .more-content-detail
      = "Si vous aussi, vous voulez ouvrir votre propre journal, merci de contacter: Laurie.Annie.Clemence@gmail.com"

app/views/reactions/index.html.slim
.title
  .title-content
    = "Réactions"

.show
  .show-content
    = @information.content
  .show-button
    = link_to "réagis", information_path(@information.id)

.index
  - @reactions.each do |reaction|
    .index-content
      .index-content-information
        = Information.find(reaction.information_id).content
      .index-content-middle
        = reaction.content
      .index-content-bottom
        = link_to "réagis", information_path(reaction.information_id)